Trab_LP_BD_v1/Controllers/CarrinhoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Newtonsoft.Json;
using Trab_LP_BD_v1.DAO;
using Trab_LP_BD_v1.Models;

namespace Trab_LP_BD_v1.Controllers
{
    public class CarrinhoController : Controller
    {

        public IActionResult Index()
        {
            ProdutosDAO dao = new ProdutosDAO();
            var listaDeProdutos = dao.Listagem();

            var carrinho = ObtemCarrinhoNaSession();

            @ViewBag.TotalCarrinho = carrinho.Sum(c => c.Quantidade);

            return View(listaDeProdutos);
        }


        public IActionResult Detalhes(int idProduto)
        {
            List<CarrinhoViewModel> carrinho = ObtemCarrinhoNaSession();

            ProdutosDAO dao = new ProdutosDAO();
            var modelProduto = dao.Consulta(idProduto);

            CarrinhoViewModel carrinhoModel = carrinho.Find(c => c.ProdutoId == idProduto);
            if (carrinhoModel == null)
            {
                carrinhoModel = new CarrinhoViewModel();
                carrinhoModel.ProdutoId = idProduto;
                carrinhoModel.Nome = modelProduto.Descricao;
                carrinhoModel.Quantidade = 0;
            }

            // preenche a imagem
            carrinhoModel.ImagemEmBase64 = modelProduto.ImageBase64;
            return View(carrinhoModel);
        }

        private List<CarrinhoViewModel> ObtemCarrinhoNaSession()
        {
            List<CarrinhoViewModel> carrinho = new List<CarrinhoViewModel>();
            string carrinhoJson = HttpContext.Session.GetString("carrinho");
            if (carrinhoJson != null)
                carrinho = JsonConvert.DeserializeObject<List<CarrinhoViewModel>>(carrinhoJson);

            return carrinho;
        }

        public IActionResult AdicionarCarrinho(int ProdutoId, int Quantidade)
        {
            List<CarrinhoViewModel> carrinho = ObtemCarrinhoNaSession();

            CarrinhoViewModel carrinhoModel = carrinho.Find(c => c.ProdutoId == ProdutoId);

            if (carrinhoModel != null && Quantidade == 0)
            {
                //tira do carrinho
                carrinho.Remove(carrinhoModel);
            }
            else if (carrinhoModel == null && Quantidade > 0)
            {
                //não havia no carrinho, vamos adicionar
                ProdutosDAO dao = new ProdutosDAO();
                var modelProduto = dao.Consulta(ProdutoId);

                carrinhoModel = new CarrinhoViewModel();
                carrinhoModel.ProdutoId = ProdutoId;
                carrinhoModel.Nome = modelProduto.Descricao;
                carrinhoModel.Valor = modelProduto.Preco * Quantidade;
                carrinho.Add(carrinhoModel);
            }

            if (carrinhoModel != null)
                carrinhoModel.Quantidade = Quantidade;

            string carrinhoJson = JsonConvert.SerializeObject(carrinho);
            HttpContext.Session.SetString("carrinho", carrinhoJson);

            return RedirectToAction("Index");
        }


        public IActionResult Visualizar()
        {
            var carrinho = ObtemCarrinhoNaSession();
            return View(carrinho);
        }


        public override void OnActionExecuting(ActionExecutingContext context)
        {
            if (!HelperControllers.VerificaUserLogado(HttpContext.Session))
                context.Result = RedirectToAction("Index", "Login");
            else
            {
                ViewBag.Logado = true;
                base.OnActionExecuting(context);
            }
        }
        public IActionResult EfetuarPedido()
        {
            using (var transacao = new System.Transactions.TransactionScope())
            {
                PedidoViewModel pedido = new PedidoViewModel();
                pedido.Data = DateTime.Now;
                PedidoDAO pedidoDAO = new PedidoDAO();
                int idPedido = pedidoDAO.Insert(pedido);
                PedidoItemDAO itemDAO = new PedidoItemDAO();
                var carrinho = ObtemCarrinhoNaSession();
                foreach (var elemento in carrinho)
                {
                    PedidoItemViewModel item = new PedidoItemViewModel();
                    item.PedidoId = idPedido;
                    item.ProdutoId = elemento.ProdutoId;
                    item.Qtde = elemento.Quantidade;
                    item.Valor = elemento.Valor;
                    itemDAO.Insert(item);
                }
                transacao.Complete();
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Trab_LP_BD_v1/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Trab_LP_BD_v1.Models;
using Trab_LP_BD_v1.DAO;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Mvc.Filters;

namespace Trab_LP_BD_v1.Controllers
{
    public class ClienteController : PadraoController<ClienteViewModel>
    {
        public ClienteController()
        {
            GeraProximoId = true;
            DAO = new ClienteDAO();
        }

        public byte[] ConvertImageToByte(IFormFile file)
        {
            if (file != null)
                using (var ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    return ms.ToArray();
                }
            else
                return null;
        }

        protected override void PreencheDadosParaView(string Operacao, ClienteViewModel model)
        {            
            base.PreencheDadosParaView(Operacao, model);
        }        
        protected override void ValidaDados(ClienteViewModel model, string operacao)
        {            

            base.ValidaDados(model, operacao);
            if (string.IsNullOrEmpty(model.Nome))
                ModelState.AddModelError("Nome", "Preencha o nome.");
            if (string.IsNullOrEmpty(model.CEP))
                ModelState.AddModelError("Cep", "Campo obrigatório.");
            if (string.IsNullOrEmpty(model.Endereco))
                ModelState.AddModelError("Endereco", "Campo obrigatório.");
            if (string.IsNullOrEmpty(model.Bairro))
                ModelState.AddModelError("Bairro", "Campo obrigatório.");
            if (string.IsNullOrEmpty(model.Cidade))
                ModelState.AddModelError("Cidade", "Campo obrigatório.");
            if (string.IsNullOrEmpty(model.Estado))
                ModelState.AddModelError("Estado", "Campo obrigatório.");
            if (string.IsNullOrEmpty(model.Telefone))
                ModelState.AddModelError("Telefone", "Informe o telefone.");
            if (string.IsNullOrEmpty(model.Email))
                ModelState.AddModelError("Email", "Informe o email.");
            if (string.IsNullOrEmpty(model.Senha))
                ModelState.AddModelError("Senha", "Informe a senha.");
            if (model.Nasc >= DateTime.Now)
                ModelState.AddModelError("Nasc", "Data Inválida.");
            if (string.IsNullOrEmpty(model.Sexo.ToString()))
                ModelState.AddModelError("Sexo", "Informe o sexo.");

            if (model.Imagem == null && operacao == "I")
                ModelState.AddModelError("Imagem", "Escolha uma imagem.");
            if (model.Imagem != null && model.Imagem.Length / 1024 / 1024 >= 2)
                ModelState.AddModelError("Imagem", "Imagem limitada a 2 mb.");
            if (ModelState.IsValid)
            {
                //na alteração, se não foi informada a imagem, iremos manter a que já estava salva.
                if (operacao == "A" && model.Imagem == null)
                {
                    ClienteViewModel cliente = DAO.Consulta(Convert.ToUInt16(model.Id));
                    model.ImagemEmByte = cliente.ImagemEmByte;
                }
                else
                {
                    model.ImagemEmByte = ConvertImageToByte(model.Imagem);
                }
            }
        }
    }
}

Trab_LP_BD_v1/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Trab_LP_BD_v1.DAO;
using Trab_LP_BD_v1.Models;

namespace Trab_LP_BD_v1.Controllers
{
    public class LoginController : Controller
    {
        ClienteDAO c = new ClienteDAO();
        public IActionResult Index()
        {            
            return View();
        }

        public IActionResult Form()
        {
            return View();
        }

        public IActionResult Salvar(LoginViewModel l)
        {
            bool existeUser = false;
            LoginDAO dao = new LoginDAO();
            try
            {
                var lista = dao.Consulta_Login(l.Usuario);

                if (lista != null)
                    if (lista.Usuario == l.Usuario)
                        existeUser = true;

                if (existeUser == false)
                    dao.Insert(l);
                else
                {
                    throw new Exception("Usuário já existente!");
                }
                return RedirectToAction("index");
            }
            catch (Exception erro)
            {
                ViewBag.Erro = "Ocorreu um erro: " + erro.Message;
                return View("Form");
            }
        }

        public IActionResult FazLogin(string email, string senha)
        {
            LoginDAO log = new LoginDAO();
            var lista = log.Consulta_Login(email);
            bool existeUser = false;

            if (lista != null)
                if (lista.Usuario == email && lista.Senha == senha)
                    existeUser = true;
                    
            //Este é apenas um exemplo, aqui você deve consultar na sua tabela de usuários
            //se existem esse usuário e senha
            if (existeUser)
            {
                HttpContext.Session.SetString("Logado", "true");
                ViewBag.Logado = HelperControllers.VerificaUserLogado(HttpContext.Session);
                return RedirectToAction("index", "Home");
            }
            else if (email == "admin" && senha == "1234")
            {
                HttpContext.Session.SetString("Admin", "true");
                ViewBag.Admin = HelperControllers.VerificaUserAdmin(HttpContext.Session);
                return RedirectToAction("index", "Home");
            }
            else
            {
                ViewBag.Erro = "Usuário ou senha inválidos!";
                return View("Index");
            }
        }        

        public IActionResult LogOff()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }
    }
}

Trab_LP_BD_v1/Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Trab_LP_BD_v1.Models;
using Trab_LP_BD_v1.DAO;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace Trab_LP_BD_v1.Controllers
{
    public class ProdutosController : PadraoController<ProdutosViewModel>
    {
        public ProdutosController()
        {
            GeraProximoId = true;
            DAO = new ProdutosDAO();
        }

        public byte[] ConvertImageToByte(IFormFile file)
        {
            if (file != null)
                using (var ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    return ms.ToArray();
                }
            else
                return null;
        }

        protected override void PreencheDadosParaView(string Operacao, ProdutosViewModel model)
        {            
            base.PreencheDadosParaView(Operacao, model);
        }
        protected override void ValidaDados(ProdutosViewModel model, string operacao)
        {
            base.ValidaDados(model, operacao);
            if (string.IsNullOrEmpty(model.Descricao))
                ModelState.AddModelError("Descricao", "Preencha a descrição.");
            if (model.CategoriaId < 0)
                ModelState.AddModelError("CategoriaId", "Campo obrigatório.");
            if (model.Preco < 0)
                ModelState.AddModelError("Preco", "Informe o preço.");

            if (model.Imagem == null && operacao == "I")
                ModelState.AddModelError("Imagem", "Escolha uma imagem.");
            if (model.Imagem != null && model.Imagem.Length / 1024 / 1024 >= 2)
                ModelState.AddModelError("Imagem", "Imagem limitada a 2 mb.");


            if (ModelState.IsValid)
            {
                //na alteração, se não foi informada a imagem, iremos manter a que já estava salva.
                if (operacao == "A" && model.Imagem == null)
                {
                    ProdutosViewModel produto = DAO.Consulta(Convert.ToUInt16(model.Id));
                    model.ImagemEmByte = produto.ImagemEmByte;
                }
                else
                {
                    model.ImagemEmByte = ConvertImageToByte(model.Imagem);
                }
            }
        }

        private void PreparaListaCategoriasParaCombo()
        {
            CategoriaDAO categoriaDao = new CategoriaDAO();
            var categorias = categoriaDao.ListaCategorias();
            List<SelectListItem> listaCategorias = new List<SelectListItem>();
            listaCategorias.Add(new SelectListItem("Selecione uma categoria...", "0"));
            foreach (var cidade in categorias)
            {
                SelectListItem item = new SelectListItem(cidade.Descricao, cidade.Id.ToString());
                listaCategorias.Add(item);
            }
            ViewBag.Categorias = listaCategorias;
        }
    }
}

Trab_LP_BD_v1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trab_LP_BD_v1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        @*/<link rel="stylesheet" href="~/css/estilo.css" />*@
        @*<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">*@
        <link rel="stylesheet" href="~/css/w3.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
        <style>
            body, h1, h2, h3, h4, h5, h6 {
                font-family: "Karma", sans-serif;
            }

            a {
                color: blue;
            }

            body {
                background-color: aliceblue;
            }

            .w3-bar-block .w3-bar-item {
                padding: 20px
            }
        </style>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    @RenderSection("styles", false)

    <script>
        // Script to open and close sidebar
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
        }

        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
        }
    </script>
</head>
<body>
    <nav class="w3-sidebar w3-bar-block w3-card w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:20%;min-width:30px" id="mySidebar">
        <a href="javascript:void(0)" onclick="w3_close()"
           class="w3-bar-item w3-button">Fechar Menu</a>

        @if (ViewBag.Logado == true)
        {
            <a asp-area="" asp-controller="Cliente" asp-action="Index" onclick="w3_close()" class="w3-bar-item w3-button">Clientes</a>
            <a asp-area="" asp-controller="Funcionario" asp-action="Index" onclick="w3_close()" class="w3-bar-item w3-button">Funcionários</a>
            <a asp-area="" asp-controller="Categoria" asp-action="Index" onclick="w3_close()" class="w3-bar-item w3-button">Categorias</a>
            <a asp-area="" asp-controller="Produtos" asp-action="Index" onclick="w3_close()" class="w3-bar-item w3-button">Produtos</a>
            <a asp-area="" asp-controller="Carrinho" asp-action="Index" onclick="w3_close()" class="w3-bar-item w3-button">Carrinho </a>
        }
        <a asp-area="" asp-controller="Home" asp-action="About" onclick="w3_close()" class="w3-bar-item w3-button">Sobre</a>

    </nav>

    <div class="w3-top">
        <div class="w3-white w3-xlarge" style="max-width:1000px;margin:auto">
            <div class="w3-button w3-padding-16 w3-left" onclick="w3_open()">☰</div>
            @if (ViewBag.Logado == true)
            {
                <div class="w3-right w3-padding-16">
                    <a asp-area="" asp-controller="Login" asp-action="LogOff" onclick="w3_close()" class="w3-bar-item w3-button"><img src="~/images/logof32.png" /></a>
                </div>
            }
            else
            {
                <div class="w3-right w3-padding-16">
                    <a asp-area="" asp-controller="Login" asp-action="Index" onclick="w3_close()" class="w3-bar-item w3-button glyphicon glyphicon-user"></a>
                </div>
            }
            <div class="w3-center w3-padding-16"><a asp-area="" asp-controller="Home" asp-action="Index" class="w3-bar-item w3-button glyphicon glyphicon-home"></a></div>
        </div>
    </div>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - FTT – Faculdade de Tecnologia Termomecanica</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>